name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: Clear description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal Reproduction
      description: Minimal code to reproduce the issue
      placeholder: |
        ```python
        from agentecs import World, component

        # Your minimal reproduction code
        ```
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: Full error message or traceback
      placeholder: Paste error output here
      render: shell

  - type: input
    id: version
    attributes:
      label: AgentECS Version
      placeholder: "0.1.0 or commit hash"

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "3.12.0"

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 22.04, macOS 14.0, Windows 11"

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
