name: Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Help us understand what you need.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: "I'm trying to [do X] but AgentECS doesn't support [Y]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        ```python
        # Example API you'd like to see
        @system()
        def my_system(world):
            # Your proposed feature usage
            pass
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you tried or considered?

  - type: textarea
    id: context
    attributes:
      label: Use Case
      description: What are you building? Why is this important?
